$schema: "https://raw.githubusercontent.com/lastmile-ai/mcp-agent/main/schema/mcp-agent.config.schema.json"

mcp:
  servers:
    ai-humanizer:
      command: /home/delorenj/.local/bin/mise
      args: ["x", "--", "npx", "-y", "@modelcontextprotocol/server-ai-humanizer"]
    divide-and-conquer:
      command: /home/delorenj/.local/bin/mise
      args: ["x", "--", "npx", "-y", "@landicefu/divide-and-conquer-mcp-server"]
    sequential-thinking:
      command: /home/delorenj/.local/bin/mise
      args: ["x", "--", "npx", "-y", "@modelcontextprotocol/server-sequential-thinking"]
    github:
      command: /home/delorenj/.local/bin/mise
      args: ["x", "--", "npx", "-y", "@modelcontextprotocol/server-github"]
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  